debug "Inside base packages"

# Everything needed (include the batteries)
dnf install -y ansible btop \
    "adcli" \
    "bash-color-prompt" \
    "bcache-tools" \
    "bootc" \
    "borgbackup" \
    "cryfs" \
    "ddcutil" \
    "evtest" \
    "fastfetch" \
    "firewall-config" \
    "fish" \
    "foo2zjs" \
    "fuse-encfs" \
    "gcc" \
    "git-credential-libsecret" \
    "glow" \
    "gum" \
    "hplip" \
    "ibus-mozc" \
    "ifuse" \
    "input-remapper" \
    "iwd" \
    "jetbrains-mono-fonts-all" \
    "krb5-workstation" \
    "libgda" \
    "libgda-sqlite" \
    "libimobiledevice" \
    "libratbag-ratbagd" \
    "libsss_autofs" \
    "libxcrypt-compat" \
    "lm_sensors" \
    "make" \
    "mozc" \
    "nerd-fonts" \
    "oddjob-mkhomedir" \
    "opendyslexic-fonts" \
    "openssh-askpass" \
    "powertop" \
    "printer-driver-brlaser" \
    "python3-pip" \
    "python3-pygit2" \
    "rclone" \
    "restic" \
    "samba" \
    "samba-dcerpc" \
    "samba-ldb-ldap-modules" \
    "samba-winbind-clients" \
    "samba-winbind-modules" \
    "setools-console" \
    "sssd-ad" \
    "sssd-krb5" \
    "sssd-nfs-idmap" \
    "tailscale" \
    "tmux" \
    "uld" \
    "usbmuxd" \
    "wireguard-tools" \
    "wl-clipboard" \
    "xprop" \
    "yaru-theme" \
    "zenity" \
    "zsh" \
    "adobe-source-code-pro-fonts" \
    "android-tools" \
    "bcc" \
    "bpftop" \
    "bpftrace" \
    "cascadia-code-fonts" \
    "cockpit-bridge" \
    "cockpit-machines" \
    "cockpit-networkmanager" \
    "cockpit-ostree" \
    "cockpit-podman" \
    "cockpit-selinux" \
    "cockpit-storaged" \
    "cockpit-system" \
    "code" \
    "dbus-x11" \
    "edk2-ovmf" \
    "flatpak-builder" \
    "genisoimage" \
    "google-droid-sans-mono-fonts" \
    "google-go-mono-fonts" \
    "ibm-plex-mono-fonts" \
    "iotop" \
    "kcli" \
    "libvirt" \
    "libvirt-nss" \
    "mozilla-fira-mono-fonts" \
    "nicstat" \
    "numactl" \
    "osbuild-selinux" \
    "p7zip" \
    "p7zip-plugins" \
    "podman" \
    "podman-bootc" \
    "podman-compose" \
    "podman-machine" \
    "podman-tui" \
    "podmansh" \
    "powerline-fonts" \
    "python3-ramalama" \
    "qemu" \
    "qemu-char-spice" \
    "qemu-device-display-virtio-gpu" \
    "qemu-device-display-virtio-vga" \
    "qemu-device-usb-redirect" \
    "qemu-img" \
    "qemu-system-x86-core" \
    "qemu-user-binfmt" \
    "qemu-user-static" \
    "rocm-hip" \
    "rocm-opencl" \
    "rocm-smi" \
    "sysprof" \
    "tiptop" \
    "trace-cmd" \
    "ubuntu-family-fonts" \
    "udica" \
    "umoci" \
    "virt-manager" \
    "virt-v2v" \
    "virt-viewer" \
    "ydotool"
    "fwupd"
# ZFS
